<?php

namespace App\Http\Requests\Admin\SuccessPartners;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class CreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            "title" => "required",
            "image" => "required",
            "url" => "required",
            "is_active" => "nullable",
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        dd($validator->errors());
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}
